### ISSUE TITLE
Field logic (combined into a checklist)

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-refund#21]
# Correct logic
- [x] Step 2 - HIDE **Workwise option** for CustomerType: PaperTicket
- [x] Step 3 - **When did you last use your ticket to travel?** appears to everybody, aside from ClassPass and ScratchCard, who will have already skipped this step
- [x] Step 3 - **What is your Swift card number?** appears to everybody, aside from CustomerType: OnlineSales (ScratchCard and ClassPass will have already skipped this step)
- [x] Step 4 - Check if API asks for **First Name** and **Last Name** for ScratchCard and ClassPass
- [x] Step 4 - **What company do you work for?** ONLY appears for CustomerType: ScratchCard, ClassPass and Corporate
- [x] Step 4 - **Date of Birth** does not show for CustomerType: ScratchCard, OnlineSales or Shop

# Trickier
- [x] Step 3 - Swift card OR Ticket number can apply for CustomerTypes: DirectDebit; Corporate; SwiftPortal and Shop; hence the reason asking if we can temporarily store whether the user said "Swift card" or "Paper ticket"

# CustomerTypes
DirectDebit (set in step 2)
Corporate (set in step 2)
OnlineSales (set in step 2)
ScratchCard (set in step 1)
ClassPass (set in step 1)
Shop (set in step 2)
SwiftPortal (set in step 1 and 2)
Workwise (set in step 2)

**Comment by daylesalmon** [comment]
What is your Swift card number? appears to everybody, aside from CustomerType: OnlineSales (ScratchCard and ClassPass will have already skipped this step)

I've left this step as Paul's API changes between ticket number and swift card. And i've matched accordingly.

**Comment by daylesalmon** [comment]
> Check if API asks for First Name and Last Name for ScratchCard and ClassPass

Neither do, i've attached the data models below...
Should I remove FirstName/LastName for these types of users on the last step?

**ScratchCard**
```json
"CustomerType": "Scratchcard",
	"Application": {
		"OrganisationName": "WMCA",
		"Email": "Jon.Doe@somewhere.there.mail",
		"LastUsedDate": "2020-03-02",
		"PhoneNumber": "0121 214 7474",
		"PhotoBase64Extension": "jpg",
		"PhotoBase64":
```

 **ClassPass**
```json
"CustomerType": "ClassPass",
	"Application": {
		"OrganisationName": "WMCA",
		"Email": "Jon.Doe@somewhere.there.mail",
		"LastUsedDate": "2020-03-02",
		"PhoneNumber": "0121 214 7474",
		"PhotoBase64Extension": "jpg",
		"PhotoBase64":	
```

**Comment by mrmjprice** [comment]
> > Check if API asks for First Name and Last Name for ScratchCard and ClassPass
> 
> Neither do, i've attached the data models below...
> Should I remove FirstName/LastName for these types of users on the last step?
> 
> **ScratchCard**
> 
> ```json
> "CustomerType": "Scratchcard",
> 	"Application": {
> 		"OrganisationName": "WMCA",
> 		"Email": "Jon.Doe@somewhere.there.mail",
> 		"LastUsedDate": "2020-03-02",
> 		"PhoneNumber": "0121 214 7474",
> 		"PhotoBase64Extension": "jpg",
> 		"PhotoBase64":
> ```
> 
> **ClassPass**
> 
> ```json
> "CustomerType": "ClassPass",
> 	"Application": {
> 		"OrganisationName": "WMCA",
> 		"Email": "Jon.Doe@somewhere.there.mail",
> 		"LastUsedDate": "2020-03-02",
> 		"PhoneNumber": "0121 214 7474",
> 		"PhotoBase64Extension": "jpg",
> 		"PhotoBase64":	
> ```

Yes, please remove. Ticketing becomes more and more complicated by the second!

**Comment by daylesalmon** [comment]
> > > Check if API asks for First Name and Last Name for ScratchCard and ClassPass
> > 
> > 
> > Neither do, i've attached the data models below...
> > Should I remove FirstName/LastName for these types of users on the last step?
> > **ScratchCard**
> > ```json
> > "CustomerType": "Scratchcard",
> > 	"Application": {
> > 		"OrganisationName": "WMCA",
> > 		"Email": "Jon.Doe@somewhere.there.mail",
> > 		"LastUsedDate": "2020-03-02",
> > 		"PhoneNumber": "0121 214 7474",
> > 		"PhotoBase64Extension": "jpg",
> > 		"PhotoBase64":
> > ```
> > 
> > 
> > **ClassPass**
> > ```json
> > "CustomerType": "ClassPass",
> > 	"Application": {
> > 		"OrganisationName": "WMCA",
> > 		"Email": "Jon.Doe@somewhere.there.mail",
> > 		"LastUsedDate": "2020-03-02",
> > 		"PhoneNumber": "0121 214 7474",
> > 		"PhotoBase64Extension": "jpg",
> > 		"PhotoBase64":	
> > ```
> 
> Yes, please remove. Ticketing becomes more and more complicated by the second!

Removed.

**Comment by daylesalmon** [comment]
> Step 4 - Date of Birth does not show for CustomerType: ScratchCard, OnlineSales or Shop

@mrmjprice : Paul has DateOfBirth in OnlineSales...
```json
"CustomerType": "OnlineSales",
	"Application": {
		"Firstname": "Jon",
		"Lastname": "Doe",
		"TicketNumber": "123456",
		"Email": "Jon.Doe@somewhere.there.mail",
		"AddressPostcode": "B19 3SD",
		"AddressLine1": "16 Summer Lane",
		"AddressLine2": "Optional",
		"AddressLine3": "Optional",
		"AddressLine4": "Optional",
		"AddressTown": "Birmingham",
		"DateOfBirth": "2000-01-01",
		"LastUsedDate": "2020-03-02",
		"PhoneNumber": "0121 214 7474",
		"PhotoBase64Extension": "jpg",
		"PhotoBase64":
```

**Comment by daylesalmon** [comment]
> Step 3 - Swift card OR Ticket number can apply for CustomerTypes: DirectDebit; Corporate; SwiftPortal and Shop; hence the reason asking if we can temporarily store whether the user said "Swift card" or "Paper ticket"

I have it so the swift card option appears for **DirectDebit, Workwise and Corporate**. Every other customer type will show ticket number.

**Comment by mrmjprice** [comment]
> > Step 4 - Date of Birth does not show for CustomerType: ScratchCard, OnlineSales or Shop
> 
> @mrmjprice : Paul has DateOfBirth in OnlineSales...
> Did you mean CustomerType ClassPass?
> 
> ```json
> "CustomerType": "OnlineSales",
> 	"Application": {
> 		"Firstname": "Jon",
> 		"Lastname": "Doe",
> 		"TicketNumber": "123456",
> 		"Email": "Jon.Doe@somewhere.there.mail",
> 		"AddressPostcode": "B19 3SD",
> 		"AddressLine1": "16 Summer Lane",
> 		"AddressLine2": "Optional",
> 		"AddressLine3": "Optional",
> 		"AddressLine4": "Optional",
> 		"AddressTown": "Birmingham",
> 		"DateOfBirth": "2000-01-01",
> 		"LastUsedDate": "2020-03-02",
> 		"PhoneNumber": "0121 214 7474",
> 		"PhotoBase64Extension": "jpg",
> 		"PhotoBase64":
> ```

I did!

**Should not show for ScratchCard, ClassPass or Shop**

**Comment by mrmjprice** [comment]
> > Step 3 - Swift card OR Ticket number can apply for CustomerTypes: DirectDebit; Corporate; SwiftPortal and Shop; hence the reason asking if we can temporarily store whether the user said "Swift card" or "Paper ticket"
> 
> I have it so the swift card option appears for **DirectDebit, Workwise and Corporate**. Every other customer type will show ticket number.

We'll ask for confirmation in the walkthrough with CS. 😄

**Comment by mrmjprice** [comment]
All closed or picked up in new ticket
