### ISSUE TITLE
Tracking/Analytics (combined list)

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-refund#29]
# General
- [x] Number of applications sent (broken down by CustomerType)

# Google Analytics
We want to track
- [x] Where people get stuck on a page? (Is it a specific field?)
- [x] Where people drop out of the process (step 1, 2, 3 or 4)?
- [x] How many people started the form and how many people submitted it?

# Hotjar
- [ ] Can Hotjar generate a heatmap?
- [ ] Can Hotjar form tracker track the form?

**Comment by mrmjprice** [comment]
![condragulations](https://media1.tenor.com/images/545cc9fa561b3384b90ea21c92d8747e/tenor.gif?itemid=5438064)
